apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: webserver
        env:
          - name: ENVONE
            value: "hellothisisDEV"
          - name: ENVTWO
            value: "i-only-have-this-in-the-dev-overlay"
          - name: ENVTHREE
            value: "i-only-have-this-in-the-dev-overlay"