apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
#namespace: dev-warehouse
namePrefix: dev-
images:
  - name: nginx
    newName: nginx
    newTag: "1.22.2"
patchesStrategicMerge:
- deployment.yaml
- service.yaml