apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
#namespace: prod-warehouse
namePrefix: prod-
images:
  - name: nginx
    newName: nginx
    newTag: "1.22"
patchesStrategicMerge:
- deployment.yaml
- service.yaml