apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  generation: 1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: webserver
        env:
          - name: ENVONE
            value: "hello"
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
